const FUNCTION_ID = {
  TOP_UP: 'TOP_UP',
  WEEK_SPEND_LIMIT: 'WEEK_SPEND_LIMIT',
  FREEZE_CARD: 'FREEZE_CARD',
  GET_NEW_CARD: 'GET_NEW_CARD',
  DEACTIVATED_CARD: 'DEACTIVATED_CARD',
};

export {FUNCTION_ID};
