enum DebitCardTypes {
  GET_BALANCE = 'GET_BALANCE',
  GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS',

  GET_CARD_INFO = 'GET_CARD_INFO',
  GET_CARD_INFO_SUCCESS = 'GET_CARD_INFO_SUCCESS',

  SAVE_SPEND_LIMIT = 'SAVE_SPEND_LIMIT',
  GET_SPEND_LIMIT = 'GET_SPEND_LIMIT',
  GET_SPEND_LIMIT_SUCCESS = 'GET_SPEND_LIMIT_SUCCESS',
  SET_IS_SPEND_LIMIT = 'SET_IS_SPEND_LIMIT',
  GET_IS_SPEND_LIMIT = 'GET_IS_SPEND_LIMIT',
  GET_IS_SPEND_LIMIT_SUCCESS = 'GET_IS_SPEND_LIMIT_SUCCESS',

  GET_CURRENT_SPEND = 'GET_CURRENT_SPEND',
  GET_CURRENT_SPEND_SUCCESS = 'GET_CURRENT_SPEND_SUCCESS',

  GET_CURRENCY = 'GET_CURRENCY',
  GET_CURRENCY_SUCCESS = 'GET_CURRENCY_SUCCESS',
}

export default DebitCardTypes;
